name: ppp github action ci

on:
  schedule:
    - cron: "0 8 1 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi

      - name: Update data
        run: make data

      - name: Commit and push updates
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated commit"
            git push origin main
          fi
